apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "alg-bind2"
spec:
  kprobes:
  - call: "security_socket_bind"
    syscall: false
    args:
    - index: 1
      type: "sockaddr"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Family"
        values:
        - "38"      #AF_ALG
      matchActions:
      - action: Post
        rateLimit: 1s